### ISSUE TITLE
gtest() error: "missing value where TRUE/FALSE needed"

### ISSUE THREAD

**Issue by ogamimusashi** [njm18/gmatrix#1]
Hello,
I installed gmatrix following the instructions, i'm on a laptop with a geforce 870M installed, cuda 6.5, manjaro distrib.

install seems ok (i got some warnings like "matrix.cu(338): warning: variable "colnames" was set but never used") but when i try gtest() it shows the error:

"Error in if (tmp > 10^-6) mywarnings = c(mywarnings, "not equal") : 
  missing value where TRUE/FALSE needed"

Any idea? Thank you!

**Comment by njm18** [comment]
Sorry, just noticed your question. Couple of questions: What version of R are you using? Have you successfully compiled and run other NVIDIA programs with you CUDA distribution? Do some of the functions such as grnorm and gorder appear to be working? 
nathan

**Comment by ogamimusashi** [comment]
Hello,

I'm using R 3.1.2 64bits (via rstudio). I've ran successfully deviceQuery samples tests that come with CUDA. I've also written an helloworld CUDA file (a simple addition on GPU) and its interfaces in R, it also works.

I've tested grnorm but it generates NaN, and gorder crashes Rstudio.

Thanks for your help!

**Comment by njm18** [comment]
Couple of things to try. First, can you try running R from the command line instead of Rstudio... just on a hunch. I have never tried to run gmatrix with Rstudio. Next, could you check that your CUDA_LIB_PATH, R_INC_PATH and NVCC_ARCH environmental were set correctly when compiling? What was NVCC_ARCH set to? Does the listDevices() function crash R? What about trying something like a=g(rnorm(100))+g(rnorm(100)) to see if addition works?

Sorry,  it isn't obvious to me what is wrong, but hopefully we can figure it out. 
nathan

**Comment by ogamimusashi** [comment]
Hello,
Trying with R base produces the same results.

My set env were set:
            Sys.setenv(CUDA_LIB_PATH="/opt/cuda/lib64/")
            Sys.setenv(R_INC_PATH="/usr/include/R/")
            Sys.setenv(NVCC_ARCH="-gencode arch=compute_30,code=sm_30")

listDevices() works (lists my 870M card)

a=g(rnorm(100).... produces Nan in the a results :)

**Comment by njm18** [comment]
I am aware that there is an error in the way the current make file uses the NVCC_ARCH environmental variable. Could you try compiling without setting that variable? I actually have rewriting the install process to use a configure file on my list of things to do. Hopefully that will make it easier to get past these issues.

**Comment by ogamimusashi** [comment]
Hello,
One very trivial question..one the NVCC_ARCH variable set, how i do i compile without setting it? (i mean do i need to delete it first? if yes, then how?)

Sorry i'm a windows guy that recently switched to linux :)

**Comment by njm18** [comment]
Just exit R, and start a new R session :-). The other two environmental variables will need to be set again for your new session. You can always look at the current state of environmental variables in R using using a command like:  Sys.getenv(x="NVCC_ARCH").

nathan

**Comment by ogamimusashi** [comment]
Hello nathan,

I tried to do that, but when i do Sys.getenv(x="NVCC_ARCH") even after exiting and restarting a new session it seems the variable setting stays.  The gtest() still fails (which may be due to do preceding factor)

**Comment by njm18** [comment]
Hopefully this is fixed in the newest version gmatrix which no longer uses environmental variables.
