### ISSUE TITLE
gtest() error

### ISSUE THREAD

**Issue by ghost** [njm18/gmatrix#2]
> library(gmatrix)
> gtest()
> Checking matrix multiplication, crossprod and tcrossprod... 
> Error in if (tmp > 10^-6) mywarnings = c(mywarnings, "not equal") : 
>   missing value where TRUE/FALSE needed

**Comment by ghost** [comment]
If this helps. This is from terminal trying to install package again, and then gtest().

> Sys.setenv(R_INC_PATH="/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/include/")
> Sys.getenv(x="R_INC_PATH")
> [1] "/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/include/"
> 
> Sys.setenv(CUDA_LIB_PATH="/usr/local/cuda-7.0/lib64/")
> Sys.getenv(x="CUDA_LIB_PATH")
> [1] "/usr/local/cuda-7.0/lib64/"
> install.packages("gmatrix")
> Installing package into ‘/home/davidm/R/x86_64-unknown-linux-gnu-library/3.1’
> (as ‘lib’ is unspecified)
> trying URL 'http://mran.revolutionanalytics.com/snapshot/2015-04-01/src/contrib/gmatrix_0.2.tar.gz'
> Content type 'application/octet-stream' length 340383 bytes (332 KB)
> 
> # opened URL
> 
> downloaded 332 KB
- installing _source_ package ‘gmatrix’ ...
  *\* package ‘gmatrix’ successfully unpacked and MD5 sums checked
  *\* libs
  *\* arch - 
  nvcc  -c dist.cu -o dist.o --shared -Xcompiler "-fPIC" -gencode arch=compute_20,code=sm_20 -O2 -I/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/include/
  nvcc  -c conversions.cu -o conversions.o --shared -Xcompiler "-fPIC" -gencode arch=compute_20,code=sm_20 -O2  -I/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/include/
  nvcc  -c general.cu -o general.o --shared -Xcompiler "-fPIC" -gencode arch=compute_20,code=sm_20 -O2 -I/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/include/
  nvcc  -c ops.cu -o ops.o --shared -Xcompiler "-fPIC" -gencode arch=compute_20,code=sm_20 -O2 -I/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/include/
  nvcc  -c manipulation.cu -o manipulation.o --shared -Xcompiler "-fPIC" -gencode arch=compute_20,code=sm_20 -O2  -I/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/include/
  nvcc  -c matrix.cu -o matrix.o --shared -Xcompiler "-fPIC" -gencode arch=compute_20,code=sm_20 -O2 -I/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/include/
  matrix.cu(322): warning: variable "ret_final" was declared but never referenced

matrix.cu(338): warning: variable "rownames" was set but never used

matrix.cu(338): warning: variable "colnames" was set but never used

matrix.cu(338): warning: variable "gpu_ptr" was declared but never referenced

matrix.cu(322): warning: variable "ret_final" was declared but never referenced

matrix.cu(338): warning: variable "rownames" was set but never used

matrix.cu(338): warning: variable "colnames" was set but never used

matrix.cu(338): warning: variable "gpu_ptr" was declared but never referenced

R CMD SHLIB dist.o conversions.o general.o ops.o manipulation.o  matrix.o -o gmatrix.so -lcudart -lcublas  -L/usr/local/cuda-7.0/lib64/
make[1]: Entering directory `/tmp/Rtmpxbzeys/R.INSTALL56fa43e88c74/gmatrix/src'
gcc -std=gnu99 -shared -L/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/lib -L/usr/local/lib -o gmatrix.so dist.o conversions.o general.o ops.o manipulation.o matrix.o -lcudart -lcublas -L/usr/local/cuda-7.0/lib64/ -L/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/lib -lR
make[1]: Leaving directory`/tmp/Rtmpxbzeys/R.INSTALL56fa43e88c74/gmatrix/src'
installing to /home/davidm/R/x86_64-unknown-linux-gnu-library/3.1/gmatrix/libs
*\* R
*\* inst
*\* preparing package for lazy loading
Creating a generic function for ‘as.matrix’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘as.vector’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘rownames’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘colnames’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘rownames<-’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘colnames<-’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘nrow’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘ncol’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘t’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘diag’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘diag<-’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘crossprod’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘tcrossprod’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘%o%’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘colSums’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘rowSums’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘colMeans’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘rowMeans’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘mean’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘sort’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘which’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘ifelse’ from package ‘base’ in package ‘gmatrix’
Creating a generic function for ‘%x%’ from package ‘base’ in package ‘gmatrix’
*\* help
**\* installing help indices
*\* building package indices
*\* testing if installed package can be loaded
Now using device 0 - "GeForce GT 740"
Starting cublas on device 0.
Creating new states on device 0.
- DONE (gmatrix)

The downloaded source packages are in
    ‘/tmp/RtmpIpeZUH/downloaded_packages’

> library(gmatrix)
> Now using device 0 - "GeForce GT 740"
> Starting cublas on device 0.
> Creating new states on device 0.
> gtest()
> Checking matrix multiplication, crossprod and tcrossprod... 
> Error in if (tmp > 10^-6) mywarnings = c(mywarnings, "not equal") : 
>   missing value where TRUE/FALSE neede

**Comment by njm18** [comment]
Sorry I never responded. I have completely rewritten the build system now. If you would like to give it a try. I have not yep pushed it to cran, but you can try:

git clone https://github.com/njm18/gmatrix.git
MAKE="make -j7" #note this make the compile process use 7 threads 
R CMD build gmatrix
R CMD INSTALL  gmatrix_0.3.tar.gz --no-test-load --configure-args="--with-arch=sm_30"

**Comment by ghost** [comment]
thanks - that got it working for me.
