### ISSUE TITLE
Selecting columns with colnames doesn't run?

### ISSUE THREAD

**Issue by KensukeOkamuraTK** [njm18/gmatrix#3]
Hello.
I use gmatrix@GitHub on TSUBAME (super computer at Tokyo Institute of Technology in Japan).

I feel good  at gmatrix,  that is good way when handling variables on GPU.
But I cannot select columns from gmatrix with colnames.
If it is bug, then I hope fix it.

``` R
library(gmatrix)
(m <- gmatrix(1:12, 3, 4))

colnames(m) <- c("a", "b", "c", "d")

m[, 3] # not run
m[, 3:4] # not run
m[, 1:4] # run
m[, T] # notrun
m[, c(T, F, T, F)] # not run
m[, c(T, T, T, T)] # run
m[, "a"] # not run
m[, c("a", "b", "c", "d")] # illeagal result 
```

**Comment by njm18** [comment]
Yep, that is clearly a bug. I will get a fix pushed out for it in a few days. Thanks for letting me know!
nathan

**Comment by njm18** [comment]
Should work now, if you use the development version. Thanks,
nathan

**Comment by KensukeOkamuraTK** [comment]
Thank you!
I 'll try immediately .
